In [ ]:
import numpy

def cal_pop_fitness(equation_inputs, pop):
    fitness = numpy.sum(pop*equation_inputs, axis=1)
    return fitness

def select_mating_pool(pop, fitness, num_parents):
    parents = numpy.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    crossover_point = numpy.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        parent1_idx = k%parents.shape[0]
        parent2_idx = (k+1)%parents.shape[0]
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

def mutation(offspring_crossover):
    for idx in range(offspring_crossover.shape[0]):
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

In [ ]:
equation_inputs = [4,-2,3.5,5,-11,-4.7]
num_weights = 6

sol_per_pop = 8
num_parents_mating = 4

pop_size = (sol_per_pop,num_weights)

new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_population)

[[ 3.92090643  3.67972996 -2.67173031 -2.40512558 -2.42754671  2.97441038]
 [ 1.48916952 -2.41529487  3.09229438  0.08640746  2.79256501  0.01761222]
 [ 2.6705288   3.79519172  1.98808333 -1.84980172 -0.0976339   2.00187064]
 [-2.40937518  1.92388315  0.92122964  2.71902366  3.9750079  -1.5209521 ]
 [-0.24207078  2.95236321 -0.58648888  2.09807824  1.73787591  0.97188336]
 [-0.79067893  3.3492489  -3.10197785  1.21145787  3.80990079 -3.98661726]
 [ 1.05023968 -3.10847198 -2.50122958 -2.24330013 -1.01726758  0.09623176]
 [ 3.82511413 -3.3587703  -1.70771954  0.20442205 -2.91029693  2.2716774 ]]


In [ ]:
num_generations = 5
for generation in range(num_generations):
    print("Generation : ", generation)
    fitness = cal_pop_fitness(equation_inputs, new_population)

    parents = select_mating_pool(new_population, fitness, 
                                      num_parents_mating)
    
    offspring_crossover = crossover(parents,
                                       offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    offspring_mutation = mutation(offspring_crossover)

    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation

    print("Best result : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))

Generation :  0
Best result :  51.85368679553216
Generation :  1
Best result :  51.85368679553216
Generation :  2
Best result :  52.82804910461524
Generation :  3
Best result :  59.06196822393739
Generation :  4
Best result :  61.76866687459792


In [ ]:
fitness = cal_pop_fitness(equation_inputs, new_population)
best_match_idx = numpy.where(fitness == numpy.max(fitness))
print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

Best solution :  [[[ 3.82511413 -3.3587703  -1.70771954  0.20442205 -5.03476924
    2.2716774 ]]]
Best solution fitness :  [61.76866687]
